name: CI MetaImage

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Odin
      run: |
        git clone https://github.com/odin-lang/Odin odin
        cd odin
        git checkout dev-2025-03
        make release-native
        echo "Installed Odin in: $(pwd)"
        echo "$(pwd)" >> $GITHUB_PATH
    - name: Run tests
      run: make test
    - name: Run example
      run: make example
    - name: Run example (debug)
      run: make example-debug
    - name: Run example2
      run: make example2
    - name: Run example2 (debug)
      run: make example2-debug

  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Odin
      run: |
        git clone https://github.com/odin-lang/Odin odin
        cd odin
        git checkout dev-2025-03
        .\build.bat release
        echo "Installed Odin in: $((Get-Location).Path)"
        echo (Get-Location).Path | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell
    - name: Run tests
      run: make test
    - name: Run example
      run: make example
    - name: Run example (debug)
      run: make example-debug
    - name: Run example2
      run: make example2
    - name: Run example2 (debug)
      run: make example2-debug
